In [42]:
import numpy as np
import pandas as pd

In [43]:
df=pd.read_csv('diabetes.csv')

In [44]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [45]:
# find realtion which feature is affecting the outcome
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

we can see tht blood pressure and skin thickness are not impacting too much we can remove them but let it be

In [46]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [47]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [48]:
X=scaler.fit_transform(X)

In [49]:
X.shape

(768, 8)

In [50]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [51]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [52]:
model=Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [53]:
model.fit(X_train,y_train,batch_size=32,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.4925 - loss: 0.7357 - val_accuracy: 0.5519 - val_loss: 0.7155
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6265 - loss: 0.6500 - val_accuracy: 0.6364 - val_loss: 0.6639
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6710 - loss: 0.6164 - val_accuracy: 0.6818 - val_loss: 0.6273
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7022 - loss: 0.5864 - val_accuracy: 0.7338 - val_loss: 0.5974
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7163 - loss: 0.5706 - val_accuracy: 0.7662 - val_loss: 0.5727
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7343 - loss: 0.5519 - val_accuracy: 0.7792 - val_loss: 0.5517
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.5174 - val_accuracy: 0.7857 - val_loss: 0.5354
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7407 - loss: 0.5272 - val_accuracy: 0.7922 - val_loss: 0.5209
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7682 - loss: 0.5054 - val_accuracy: 0.8052 - val_loss: 0.5108
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7733 - loss: 0.4896 - val_accuracy: 0.8247 - val_loss: 0.5041
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7674 - loss: 0.4911 - val_accuracy: 0.8247 - val_loss: 0.4973
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7579 - loss: 0.4770 - val_accuracy: 0.8182 - val_loss: 0.4913
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7771 - loss: 0.4698 - val_accuracy: 0.8117 - val_loss: 0.4873
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7713 - loss: 0.4777 - val_accuracy: 0.8052 - val_loss: 0.4829
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7895 - loss: 0.4498 - val_accuracy: 0.8247 - val_loss: 0.4806
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7628 - loss: 0.4681 - val_accuracy: 0.8247 - val_loss: 0.4792
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7690 - loss: 0.4693 - val_accuracy: 0.8247 - val_loss: 0.4774
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7884 - loss: 0.4373 - val_accuracy: 0.8182 - val_loss: 0.4758
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8031 - loss: 0.4303 - val_accuracy: 0.8182 - val_loss: 0.4750
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7828 - loss: 0.4521 - val_accuracy: 0.8052 - val_loss: 0.4731
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7972 - loss: 0.4478 - val_accuracy: 0.8182 - val_loss: 0.4728
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7861 - loss: 0.4436 - val_accuracy: 0.8182 - val_loss: 0.4727
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7816 - loss: 0.4504 - val_accuracy: 0.8117 - val_loss: 0.4719
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7512 - loss: 0.4611 - val_accuracy: 0.8052 - val_loss: 0.4706
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7566 - loss: 0.4774 - val_accuracy: 0.8117 - val_loss: 0.4699
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7960 - loss: 0.4383 - val_accuracy: 0.8117 - val_loss: 0.4695
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7477 - loss: 0.4963 - val_accuracy: 0.8117 - val_loss: 0.4688
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7848 - loss: 0.4423 - val_accuracy: 0.8117 - val_loss: 0.4676
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7666 - loss: 0.4488 - val_accuracy: 0.8052 - val_loss: 0.4675
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7801 - loss: 0.4587 - val_accuracy: 0.8052 - val_loss: 0.4667
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7473 - loss: 0.4667 - val_accuracy: 0.8052 - val_loss: 0.4674
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7764 - loss: 0.4437 - val_accuracy: 0.8052 - val_loss: 0.4680
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7870 - loss: 0.4137 - val_accuracy: 0.8182 - val_loss: 0.4673
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7647 - loss: 0.4458 - val_accuracy: 0.8117 - val_loss: 0.4676
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7842 - loss: 0.4410 - val_accuracy: 0.8182 - val_loss: 0.4669
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7966 - loss: 0.4149 - val_accuracy: 0.8117 - val_loss: 0.4649
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7616 - loss: 0.4312 - val_accuracy: 0.8117 - val_loss: 0.4658
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7565 - loss: 0.4564 - val_accuracy: 0.8117 - val_loss: 0.4654
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7556 - loss: 0.4676 - val_accuracy: 0.8117 - val_loss: 0.4640
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7884 - loss: 0.4212 - val_accuracy: 0.8117 - val_loss: 0.4627
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7792 - loss: 0.4230 - val_accuracy: 0.8052 - val_loss: 0.4622
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7707 - loss: 0.4545 - val_accuracy: 0.8117 - val_loss: 0.4613
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7639 - loss: 0.4248 - val_accuracy: 0.8117 - val_loss: 0.4618
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7778 - loss: 0.4215 - val_accuracy: 0.8117 - val_loss: 0.4615
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7709 - loss: 0.4436 - val_accuracy: 0.8052 - val_loss: 0.4613
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7840 - loss: 0.4485 - val_accuracy: 0.8052 - val_loss: 0.4608
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7918 - loss: 0.4268 - val_accuracy: 0.8117 - val_loss: 0.4613
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7744 - loss: 0.4616 - val_accuracy: 0.8117 - val_loss: 0.4609
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7554 - loss: 0.4619 - val_accuracy: 0.8182 - val_loss: 0.4618
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7489 - loss: 0.4618 - val_accuracy: 0.8117 - val_loss: 0.4615
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7762 - loss: 0.4527 - val_accuracy: 0.8052 - val_loss: 0.4622
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7558 - loss: 0.4567 - val_accuracy: 0.8052 - val_loss: 0.4612
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7609 - loss: 0.4489 - val_accuracy: 0.8052 - val_loss: 0.4622
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7538 - loss: 0.4509 - val_accuracy: 0.8117 - val_loss: 0.4628
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7628 - loss: 0.4537 - val_accuracy: 0.8052 - val_loss: 0.4634
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7844 - loss: 0.4167 - val_accuracy: 0.8117 - val_loss: 0.4639
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7804 - loss: 0.4127 - val_accuracy: 0.8117 - val_loss: 0.4633
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7847 - loss: 0.4094 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7728 - loss: 0.4332 - val_accuracy: 0.8052 - val_loss: 0.4637
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7653 - loss: 0.4473 - val_accuracy: 0.8117 - val_loss: 0.4627
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4194 - val_accuracy: 0.8117 - val_loss: 0.4627
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7591 - loss: 0.4296 - val_accuracy: 0.7987 - val_loss: 0.4628
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7951 - loss: 0.4221 - val_accuracy: 0.8117 - val_loss: 0.4613
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7776 - loss: 0.4440 - val_accuracy: 0.7987 - val_loss: 0.4617
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7806 - loss: 0.4506 - val_accuracy: 0.8052 - val_loss: 0.4625
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7862 - loss: 0.4195 - val_accuracy: 0.8052 - val_loss: 0.4625
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7797 - loss: 0.4249 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7726 - loss: 0.4396 - val_accuracy: 0.8052 - val_loss: 0.4638
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7741 - loss: 0.4403 - val_accuracy: 0.8052 - val_loss: 0.4624
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4339 - val_accuracy: 0.7987 - val_loss: 0.4626
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7712 - loss: 0.4349 - val_accuracy: 0.8052 - val_loss: 0.4620
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7926 - loss: 0.4181 - val_accuracy: 0.7987 - val_loss: 0.4625
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8158 - loss: 0.3988 - val_accuracy: 0.8052 - val_loss: 0.4625
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7844 - loss: 0.4150 - val_accuracy: 0.7987 - val_loss: 0.4626
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7860 - loss: 0.4153 - val_accuracy: 0.8052 - val_loss: 0.4624
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7935 - loss: 0.4114 - val_accuracy: 0.8052 - val_loss: 0.4646
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7855 - loss: 0.4452 - val_accuracy: 0.8052 - val_loss: 0.4639
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7760 - loss: 0.4308 - val_accuracy: 0.8052 - val_loss: 0.4622
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8085 - loss: 0.3809 - val_accuracy: 0.8117 - val_loss: 0.4632
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4048 - val_accuracy: 0.8117 - val_loss: 0.4625
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7881 - loss: 0.4133 - val_accuracy: 0.8182 - val_loss: 0.4624
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7981 - loss: 0.4061 - val_accuracy: 0.8117 - val_loss: 0.4622
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7753 - loss: 0.4261 - val_accuracy: 0.8117 - val_loss: 0.4619
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7863 - loss: 0.4208 - val_accuracy: 0.8117 - val_loss: 0.4621
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7762 - loss: 0.4377 - val_accuracy: 0.8117 - val_loss: 0.4622
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7624 - loss: 0.4568 - val_accuracy: 0.7987 - val_loss: 0.4614
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7858 - loss: 0.4382 - val_accuracy: 0.8052 - val_loss: 0.4595
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7958 - loss: 0.4120 - val_accuracy: 0.8052 - val_loss: 0.4592
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7966 - loss: 0.4159 - val_accuracy: 0.7987 - val_loss: 0.4594
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7801 - loss: 0.4287 - val_accuracy: 0.7987 - val_loss: 0.4604
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7912 - loss: 0.4144 - val_accuracy: 0.8052 - val_loss: 0.4602
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7971 - loss: 0.4195 - val_accuracy: 0.8052 - val_loss: 0.4601
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7880 - loss: 0.4136 - val_accuracy: 0.8117 - val_loss: 0.4615
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7853 - loss: 0.4308 - val_accuracy: 0.8052 - val_loss: 0.4624
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7755 - loss: 0.4245 - val_accuracy: 0.8117 - val_loss: 0.4623
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7694 - loss: 0.4398 - val_accuracy: 0.8052 - val_loss: 0.4604
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8059 - loss: 0.4108 - val_accuracy: 0.8117 - val_loss: 0.4617
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8032 - loss: 0.3967 - val_accuracy: 0.8117 - val_loss: 0.4619
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8113 - loss: 0.3945 - val_accuracy: 0.8052 - val_loss: 0.4610
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7816 - loss: 0.4218 - val_accuracy: 0.8052 - val_loss: 0.4614

after doing this much we are clue less. we need to decide the no of layer no of nodes,optimizer, activation,loss etc. we can automate all this using keras tuner library by using this we will find the best suitable parametr value of our model.

**
1. how to select appropriate optimizer.
2. no of nodes in a layer.
3. how to select no of layers.
4. all in one model.
**

In [54]:
pip install keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (25.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.76.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.5)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.15.1)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.18.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2025.11.12)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [55]:
import kerastuner as kt

In [56]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def build_model(hp):
    model = Sequential()

    # Input layer
    model.add(Dense(
        units=32,
        activation='relu',
        input_shape=(8,)
    ))

    # Output layer
    model.add(Dense(1, activation='sigmoid'))

    # Hyperparameter for optimizer
    optimizer = hp.Choice(
        'optimizer',
        values=['adam', 'sgd', 'rmsprop', 'adadelta']
    )

    # Compile model
    model.compile(
        optimizer=optimizer,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [57]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy', max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [58]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [59]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'sgd'}

In [60]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [61]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [62]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.6625 - loss: 0.5940 - val_accuracy: 0.7013 - val_loss: 0.5854
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.6952 - loss: 0.5766 - val_accuracy: 0.7208 - val_loss: 0.5776
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7162 - loss: 0.5638 - val_accuracy: 0.7273 - val_loss: 0.5709
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7338 - loss: 0.5338 - val_accuracy: 0.7532 - val_loss: 0.5649
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7189 - loss: 0.5539 - val_accuracy: 0.7597 - val_loss: 0.5593
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7193 - loss: 0.5480 - val_accuracy: 0.7597 - val_loss: 0.5543
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7341 - loss: 0.5320 - val_accuracy: 0.7597 - val_loss: 0.5497
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7618 - loss: 0.5224 - val_accuracy: 0.7597 - val_loss: 0.5460
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7455 - loss: 0.5309 - val_accuracy: 0.7662 - val_loss: 0.5421
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7439 - loss: 0.5295 - val_accuracy: 0.7727 - val_loss: 0.5381
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7292 - loss: 0.5317 - val_accuracy: 0.7662 - val_loss: 0.5348
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7520 - loss: 0.5171 - val_accuracy: 0.7597 - val_loss: 0.5315
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7706 - loss: 0.4973 - val_accuracy: 0.7532 - val_loss: 0.5287
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7615 - loss: 0.5055 - val_accuracy: 0.7597 - val_loss: 0.5263
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7635 - loss: 0.5046 - val_accuracy: 0.7597 - val_loss: 0.5239
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7326 - loss: 0.5148 - val_accuracy: 0.7662 - val_loss: 0.5218
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7654 - loss: 0.4734 - val_accuracy: 0.7403 - val_loss: 0.5193
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7877 - loss: 0.4869 - val_accuracy: 0.7597 - val_loss: 0.5173
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7624 - loss: 0.4924 - val_accuracy: 0.7468 - val_loss: 0.5150
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7440 - loss: 0.5149 - val_accuracy: 0.7532 - val_loss: 0.5131
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7673 - loss: 0.4790 - val_accuracy: 0.7532 - val_loss: 0.5113
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7527 - loss: 0.4878 - val_accuracy: 0.7597 - val_loss: 0.5093
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7284 - loss: 0.5193 - val_accuracy: 0.7597 - val_loss: 0.5077
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7480 - loss: 0.5106 - val_accuracy: 0.7597 - val_loss: 0.5062
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7806 - loss: 0.4734 - val_accuracy: 0.7792 - val_loss: 0.5048
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7463 - loss: 0.5048 - val_accuracy: 0.7727 - val_loss: 0.5037
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7559 - loss: 0.4868 - val_accuracy: 0.7792 - val_loss: 0.5022
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7514 - loss: 0.4895 - val_accuracy: 0.7857 - val_loss: 0.5009
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7380 - loss: 0.5070 - val_accuracy: 0.7857 - val_loss: 0.4997
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7703 - loss: 0.4743 - val_accuracy: 0.7857 - val_loss: 0.4987
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7755 - loss: 0.4795 - val_accuracy: 0.7857 - val_loss: 0.4975
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7534 - loss: 0.4860 - val_accuracy: 0.7792 - val_loss: 0.4965
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7792 - loss: 0.4536 - val_accuracy: 0.7857 - val_loss: 0.4954
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7693 - loss: 0.4786 - val_accuracy: 0.7857 - val_loss: 0.4942
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7667 - loss: 0.4685 - val_accuracy: 0.7857 - val_loss: 0.4930
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7702 - loss: 0.4754 - val_accuracy: 0.7857 - val_loss: 0.4923
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7685 - loss: 0.4631 - val_accuracy: 0.7922 - val_loss: 0.4913
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7379 - loss: 0.5010 - val_accuracy: 0.7922 - val_loss: 0.4904
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7552 - loss: 0.4831 - val_accuracy: 0.7987 - val_loss: 0.4898
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7623 - loss: 0.4693 - val_accuracy: 0.7922 - val_loss: 0.4892
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7867 - loss: 0.4632 - val_accuracy: 0.7922 - val_loss: 0.4884
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7462 - loss: 0.4896 - val_accuracy: 0.7922 - val_loss: 0.4876
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7660 - loss: 0.4728 - val_accuracy: 0.7922 - val_loss: 0.4870
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7536 - loss: 0.4741 - val_accuracy: 0.7922 - val_loss: 0.4866
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7702 - loss: 0.4670 - val_accuracy: 0.7922 - val_loss: 0.4861
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7531 - loss: 0.4878 - val_accuracy: 0.7922 - val_loss: 0.4856
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8028 - loss: 0.4518 - val_accuracy: 0.7922 - val_loss: 0.4849
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7686 - loss: 0.4562 - val_accuracy: 0.7922 - val_loss: 0.4843
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7870 - loss: 0.4462 - val_accuracy: 0.7922 - val_loss: 0.4838
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7870 - loss: 0.4540 - val_accuracy: 0.7922 - val_loss: 0.4833
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7758 - loss: 0.4659 - val_accuracy: 0.7922 - val_loss: 0.4827
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7560 - loss: 0.4731 - val_accuracy: 0.7922 - val_loss: 0.4821
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7498 - loss: 0.4870 - val_accuracy: 0.7922 - val_loss: 0.4819
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7358 - loss: 0.4887 - val_accuracy: 0.7922 - val_loss: 0.4816
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7885 - loss: 0.4390 - val_accuracy: 0.7922 - val_loss: 0.4809
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7431 - loss: 0.4869 - val_accuracy: 0.7922 - val_loss: 0.4805
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7476 - loss: 0.4607 - val_accuracy: 0.7922 - val_loss: 0.4801
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7484 - loss: 0.4569 - val_accuracy: 0.7922 - val_loss: 0.4800
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7454 - loss: 0.4721 - val_accuracy: 0.7922 - val_loss: 0.4792
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7383 - loss: 0.4606 - val_accuracy: 0.7922 - val_loss: 0.4789
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7345 - loss: 0.4836 - val_accuracy: 0.7922 - val_loss: 0.4786
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7607 - loss: 0.4468 - val_accuracy: 0.7922 - val_loss: 0.4782
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7876 - loss: 0.4415 - val_accuracy: 0.7922 - val_loss: 0.4778
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7562 - loss: 0.4580 - val_accuracy: 0.7922 - val_loss: 0.4776
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7389 - loss: 0.4759 - val_accuracy: 0.7922 - val_loss: 0.4772
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7538 - loss: 0.4733 - val_accuracy: 0.7857 - val_loss: 0.4771
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7445 - loss: 0.4742 - val_accuracy: 0.7857 - val_loss: 0.4769
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7559 - loss: 0.4578 - val_accuracy: 0.7857 - val_loss: 0.4764
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7313 - loss: 0.4841 - val_accuracy: 0.7857 - val_loss: 0.4760
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7643 - loss: 0.4507 - val_accuracy: 0.7857 - val_loss: 0.4757
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7776 - loss: 0.4435 - val_accuracy: 0.7857 - val_loss: 0.4753
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7658 - loss: 0.4532 - val_accuracy: 0.7857 - val_loss: 0.4750
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7579 - loss: 0.4825 - val_accuracy: 0.7857 - val_loss: 0.4746
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7488 - loss: 0.4643 - val_accuracy: 0.7857 - val_loss: 0.4743
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7644 - loss: 0.4576 - val_accuracy: 0.7857 - val_loss: 0.4736
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7497 - loss: 0.4667 - val_accuracy: 0.7857 - val_loss: 0.4734
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7794 - loss: 0.4584 - val_accuracy: 0.7857 - val_loss: 0.4730
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7395 - loss: 0.4853 - val_accuracy: 0.7857 - val_loss: 0.4725
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7666 - loss: 0.4513 - val_accuracy: 0.7857 - val_loss: 0.4720
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7514 - loss: 0.4703 - val_accuracy: 0.7857 - val_loss: 0.4718
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7266 - loss: 0.4658 - val_accuracy: 0.7857 - val_loss: 0.4716
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7721 - loss: 0.4557 - val_accuracy: 0.7857 - val_loss: 0.4714
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7791 - loss: 0.4454 - val_accuracy: 0.7857 - val_loss: 0.4712
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7597 - loss: 0.4438 - val_accuracy: 0.7857 - val_loss: 0.4709
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7803 - loss: 0.4314 - val_accuracy: 0.7857 - val_loss: 0.4706
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7611 - loss: 0.4618 - val_accuracy: 0.7792 - val_loss: 0.4705
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7698 - loss: 0.4588 - val_accuracy: 0.7792 - val_loss: 0.4703
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7603 - loss: 0.4554 - val_accuracy: 0.7857 - val_loss: 0.4700
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7726 - loss: 0.4465 - val_accuracy: 0.7792 - val_loss: 0.4698
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7440 - loss: 0.4717 - val_accuracy: 0.7857 - val_loss: 0.4695
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7652 - loss: 0.4560 - val_accuracy: 0.7857 - val_loss: 0.4695
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7776 - loss: 0.4565 - val_accuracy: 0.7792 - val_loss: 0.4692
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4743 - val_accuracy: 0.7792 - val_loss: 0.4689
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7725 - loss: 0.4399 - val_accuracy: 0.7792 - val_loss: 0.4687

In [67]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# right number of neurons
def build_model(hp):
    model = Sequential()

    units = hp.Int(
        'units',
        min_value=8,
        max_value=128,
        step=8
    )

    model.add(Dense(
        units=units,
        activation='relu',
        input_shape=(8,)
    ))

    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer='rmsprop',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [69]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,directory='mydir',project_name='Diabetes')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [70]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.6753246784210205

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 20s

In [71]:
tuner.get_best_hyperparameters()[0].values

{'units': 88}

In [74]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [75]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6)

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - accuracy: 0.7624 - loss: 0.5629
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.7603 - loss: 0.5117
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7621 - loss: 0.4915
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7677 - loss: 0.4839
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7863 - loss: 0.4640
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7667 - loss: 0.4776
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8012 - loss: 0.4507
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7910 - loss: 0.4452
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7721 - loss: 0.4673
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7437 - loss: 0.4826
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7648 - loss: 0.4747
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7558 - loss: 0.4844
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7797 - loss: 0.4371
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7605 - loss: 0.4530
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7381 - loss: 0.4803
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7879 - loss: 0.4448
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7813 - loss: 0.4317
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7970 - loss: 0.4186
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7667 - loss: 0.4572
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7754 - loss: 0.4539
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7735 - loss: 0.4591
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7783 - loss: 0.4213
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7718 - loss: 0.4524
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7817 - loss: 0.4531
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7778 - loss: 0.4423
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7909 - loss: 0.4108
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7901 - loss: 0.4302
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7768 - loss: 0.4540
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7959 - loss: 0.4143
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7739 - loss: 0.4316
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7765 - loss: 0.4291
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8042 - loss: 0.3998
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7753 - loss: 0.4403
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7566 - loss: 0.4322
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7778 - loss: 0.4330
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7756 - loss: 0.4348
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8064 - loss: 0.3902
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7900 - loss: 0.4291
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7791 - loss: 0.4460
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7871 - loss: 0.4188
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8112 - loss: 0.4039
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8087 - loss: 0.4052
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7965 - loss: 0.4206
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7972 - loss: 0.4349
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8025 - loss: 0.4071
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7868 - loss: 0.4258
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7672 - loss: 0.4469
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8113 - loss: 0.4151
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4313
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8077 - loss: 0.4203
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7923 - loss: 0.4123
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8059 - loss: 0.4059
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8032 - loss: 0.4088
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8096 - loss: 0.4046
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8034 - loss: 0.4155
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7843 - loss: 0.4228
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7943 - loss: 0.4024
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8152 - loss: 0.4018
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8135 - loss: 0.3928
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7911 - loss: 0.4234
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7792 - loss: 0.4451
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8031 - loss: 0.4165
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7976 - loss: 0.4272
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8022 - loss: 0.4123
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8040 - loss: 0.3999
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7906 - loss: 0.4244
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8178 - loss: 0.4037
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7938 - loss: 0.4210
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8036 - loss: 0.4099
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8024 - loss: 0.4281
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7969 - loss: 0.4375
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8089 - loss: 0.3948
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7977 - loss: 0.4139
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7962 - loss: 0.4112
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8053 - loss: 0.4167
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8051 - loss: 0.4282
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7905 - loss: 0.4395
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7914 - loss: 0.4258
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8182 - loss: 0.3694
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4197
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8034 - loss: 0.4016
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7999 - loss: 0.4181
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8284 - loss: 0.3794
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8223 - loss: 0.4023
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8056 - loss: 0.3875
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7973 - loss: 0.4242
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8286 - loss: 0.3763
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8274 - loss: 0.3822
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8459 - loss: 0.3568
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8077 - loss: 0.3940
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8212 - loss: 0.3810
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7974 - loss: 0.4025
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8257 - loss: 0.3877
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8088 - loss: 0.4015

In [78]:
# how to select no of layer
def build_model(hp):
  model=Sequential()
  model.add(Dense(88,activation='relu',input_dim=8))
  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    model.add(Dense(88,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [79]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3,directory='mydir',project_name='num_layers')

In [80]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 05s]
val_accuracy: 0.8051947951316833

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 17s

In [81]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 9}

In [82]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 24 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [83]:
model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 7s 53ms/step - accuracy: 0.7474 - loss: 0.5010 - val_accuracy: 0.7857 - val_loss: 0.4990
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8025 - loss: 0.4082 - val_accuracy: 0.7403 - val_loss: 0.5741
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7913 - loss: 0.4131 - val_accuracy: 0.7922 - val_loss: 0.4966
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.8210 - loss: 0.3797 - val_accuracy: 0.8052 - val_loss: 0.4982
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.8422 - loss: 0.3730 - val_accuracy: 0.7857 - val_loss: 0.5262
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8425 - loss: 0.3725 - val_accuracy: 0.7662 - val_loss: 0.6761
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8284 - loss: 0.4163 - val_accuracy: 0.7857 - val_loss: 0.5681
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8718 - loss: 0.3285 - val_accuracy: 0.7857 - val_loss: 0.5482
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8603 - loss: 0.3164 - val_accuracy: 0.7338 - val_loss: 0.6227
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8693 - loss: 0.3232 - val_accuracy: 0.7532 - val_loss: 0.5601
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8862 - loss: 0.2881 - val_accuracy: 0.7273 - val_loss: 0.7990
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.8841 - loss: 0.3306 - val_accuracy: 0.7208 - val_loss: 0.6324
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.8918 - loss: 0.2775 - val_accuracy: 0.7468 - val_loss: 0.7238
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8734 - loss: 0.3031 - val_accuracy: 0.7208 - val_loss: 0.8026
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9128 - loss: 0.2083 - val_accuracy: 0.6883 - val_loss: 0.7555
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9080 - loss: 0.2034 - val_accuracy: 0.6558 - val_loss: 0.6782
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8663 - loss: 0.2640 - val_accuracy: 0.7727 - val_loss: 0.6181
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9258 - loss: 0.2014 - val_accuracy: 0.7727 - val_loss: 0.7502
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.9578 - loss: 0.1365 - val_accuracy: 0.7338 - val_loss: 0.9258
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9200 - loss: 0.1867 - val_accuracy: 0.7662 - val_loss: 0.8892
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9447 - loss: 0.1696 - val_accuracy: 0.7662 - val_loss: 1.0766
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9446 - loss: 0.1480 - val_accuracy: 0.6948 - val_loss: 0.9878
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9266 - loss: 0.1522 - val_accuracy: 0.7597 - val_loss: 1.0163
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9665 - loss: 0.0977 - val_accuracy: 0.7013 - val_loss: 1.0713
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9573 - loss: 0.1186 - val_accuracy: 0.7662 - val_loss: 1.1030
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9577 - loss: 0.1135 - val_accuracy: 0.7403 - val_loss: 1.0226
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9725 - loss: 0.0780 - val_accuracy: 0.7792 - val_loss: 1.4728
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9661 - loss: 0.0968 - val_accuracy: 0.7403 - val_loss: 1.1033
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9602 - loss: 0.1022 - val_accuracy: 0.7013 - val_loss: 2.0337
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9516 - loss: 0.1491 - val_accuracy: 0.7468 - val_loss: 1.3228
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9657 - loss: 0.0899 - val_accuracy: 0.6753 - val_loss: 1.1741
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9623 - loss: 0.1025 - val_accuracy: 0.7273 - val_loss: 1.4822
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9879 - loss: 0.0406 - val_accuracy: 0.6883 - val_loss: 1.6531
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9552 - loss: 0.1466 - val_accuracy: 0.7338 - val_loss: 1.7056
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9902 - loss: 0.0373 - val_accuracy: 0.7143 - val_loss: 1.6552
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9543 - loss: 0.1076 - val_accuracy: 0.6948 - val_loss: 2.0340
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9571 - loss: 0.0994 - val_accuracy: 0.7403 - val_loss: 2.1873
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9721 - loss: 0.0994 - val_accuracy: 0.7468 - val_loss: 1.7333
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9725 - loss: 0.0749 - val_accuracy: 0.7078 - val_loss: 1.6937
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9778 - loss: 0.0575 - val_accuracy: 0.7273 - val_loss: 1.3725
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9779 - loss: 0.0697 - val_accuracy: 0.7532 - val_loss: 1.5461
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9923 - loss: 0.0215 - val_accuracy: 0.7013 - val_loss: 1.9200
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9776 - loss: 0.0674 - val_accuracy: 0.7013 - val_loss: 1.5048
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9832 - loss: 0.0427 - val_accuracy: 0.7403 - val_loss: 1.9527
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9820 - loss: 0.0344 - val_accuracy: 0.7338 - val_loss: 2.1809
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9616 - loss: 0.1408 - val_accuracy: 0.7273 - val_loss: 1.8089
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9932 - loss: 0.0316 - val_accuracy: 0.6688 - val_loss: 1.8383
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9722 - loss: 0.0579 - val_accuracy: 0.7403 - val_loss: 1.9234
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9800 - loss: 0.0590 - val_accuracy: 0.7857 - val_loss: 1.5892
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9679 - loss: 0.0888 - val_accuracy: 0.7403 - val_loss: 1.5838
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9980 - loss: 0.0128 - val_accuracy: 0.7273 - val_loss: 2.3850
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9867 - loss: 0.0487 - val_accuracy: 0.7273 - val_loss: 1.9573
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9884 - loss: 0.0417 - val_accuracy: 0.7143 - val_loss: 1.9252
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9918 - loss: 0.0439 - val_accuracy: 0.7468 - val_loss: 1.6545
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9940 - loss: 0.0241 - val_accuracy: 0.7208 - val_loss: 1.5664
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9889 - loss: 0.0280 - val_accuracy: 0.7597 - val_loss: 2.0943
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9960 - loss: 0.0201 - val_accuracy: 0.7403 - val_loss: 2.0131
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9964 - loss: 0.0189 - val_accuracy: 0.7208 - val_loss: 2.1556
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9811 - loss: 0.0737 - val_accuracy: 0.7727 - val_loss: 1.5649
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9924 - loss: 0.0208 - val_accuracy: 0.7597 - val_loss: 2.0735
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9949 - loss: 0.0139 - val_accuracy: 0.7208 - val_loss: 2.2663
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9813 - loss: 0.0417 - val_accuracy: 0.7143 - val_loss: 2.2388
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9813 - loss: 0.0506 - val_accuracy: 0.7532 - val_loss: 1.8428
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9877 - loss: 0.0347 - val_accuracy: 0.7532 - val_loss: 2.0773
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9869 - loss: 0.0320 - val_accuracy: 0.7273 - val_loss: 1.6357
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9660 - loss: 0.0757 - val_accuracy: 0.7338 - val_loss: 1.7776
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9895 - loss: 0.0204 - val_accuracy: 0.7273 - val_loss: 2.2262
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9961 - loss: 0.0106 - val_accuracy: 0.7273 - val_loss: 2.4229
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9839 - loss: 0.0581 - val_accuracy: 0.7403 - val_loss: 2.4186
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9982 - loss: 0.0058 - val_accuracy: 0.7143 - val_loss: 2.8148
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9940 - loss: 0.0137 - val_accuracy: 0.7208 - val_loss: 2.6796
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9781 - loss: 0.0812 - val_accuracy: 0.7143 - val_loss: 2.0987
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9977 - loss: 0.0075 - val_accuracy: 0.7078 - val_loss: 2.5836
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9992 - loss: 0.0041 - val_accuracy: 0.7273 - val_loss: 2.3730
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9967 - loss: 0.0181 - val_accuracy: 0.7597 - val_loss: 1.9137
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9877 - loss: 0.0260 - val_accuracy: 0.7208 - val_loss: 2.1193
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9848 - loss: 0.0687 - val_accuracy: 0.7468 - val_loss: 2.0068
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9939 - loss: 0.0294 - val_accuracy: 0.6818 - val_loss: 2.0037
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9871 - loss: 0.0461 - val_accuracy: 0.7338 - val_loss: 2.4158
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9914 - loss: 0.0796 - val_accuracy: 0.7338 - val_loss: 2.0067
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9985 - loss: 0.0052 - val_accuracy: 0.7208 - val_loss: 2.3969
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9821 - loss: 0.0388 - val_accuracy: 0.7468 - val_loss: 1.9648
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9954 - loss: 0.0203 - val_accuracy: 0.7013 - val_loss: 1.6836
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9946 - loss: 0.0274 - val_accuracy: 0.7338 - val_loss: 2.1482
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9995 - loss: 0.0018 - val_accuracy: 0.7078 - val_loss: 2.6580
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9863 - loss: 0.0632 - val_accuracy: 0.7208 - val_loss: 1.8012
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9985 - loss: 0.0099 - val_accuracy: 0.7273 - val_loss: 1.9777
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.7078 - val_loss: 2.5283
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9978 - loss: 0.0066 - val_accuracy: 0.7338 - val_loss: 2.4793
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9991 - loss: 0.0048 - val_accuracy: 0.7468 - val_loss: 2.6625
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9823 - loss: 0.0877 - val_accuracy: 0.7338 - val_loss: 2.4253
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.7078 - val_loss: 2.7719
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 4.0736e-04 - val_accuracy: 0.7078 - val_loss: 3.0754
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.6202e-04 - val_accuracy: 0.7013 - val_loss: 3.3521

In [95]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

def build_model(hp):
    model = Sequential()

    # Number of hidden layers
    num_layers = hp.Int('num_layers', min_value=1, max_value=10)

    for i in range(num_layers):
        units = hp.Int(f'units_{i}', min_value=8, max_value=128, step=8)
        activation = hp.Choice(f'activation_{i}', ['relu', 'tanh', 'sigmoid'])
        dropout_rate = hp.Float(f'dropout_{i}', min_value=0.0, max_value=0.5, step=0.1)

        if i == 0:
            model.add(Dense(
                units=units,
                activation=activation,
                input_shape=(8,)
            ))
        else:
            model.add(Dense(
                units=units,
                activation=activation
            ))

        model.add(Dropout(dropout_rate))

    # Output layer
    model.add(Dense(1, activation='sigmoid'))

    # Compile model
    model.compile(
        optimizer=hp.Choice(
            'optimizer',
            values=['adam', 'rmsprop', 'nadam', 'sgd']
        ),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [97]:
tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=3,
                      directory='mydir',
                      project_name='final'

                      )

Reloading Tuner from mydir/final/tuner0.json

In [98]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [99]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units_0': 120,
 'activation_0': 'tanh',
 'optimizer': 'nadam',
 'units_1': 8,
 'activation_1': 'relu',
 'units_2': 8,
 'activation_2': 'relu'}

In [100]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'nadam', because it has 2 variables whereas the saved optimizer has 19 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [101]:
model.fit(X_train,y_train,epochs=200,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 0.7746 - loss: 0.6390 - val_accuracy: 0.7922 - val_loss: 0.6185
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7667 - loss: 0.6413 - val_accuracy: 0.7792 - val_loss: 0.6142
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8078 - loss: 0.6134 - val_accuracy: 0.7662 - val_loss: 0.6096
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7756 - loss: 0.6168 - val_accuracy: 0.7468 - val_loss: 0.5991
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7803 - loss: 0.6084 - val_accuracy: 0.7532 - val_loss: 0.5807
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7876 - loss: 0.5830 - val_accuracy: 0.7597 - val_loss: 0.5546
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7958 - loss: 0.5585 - val_accuracy: 0.7597 - val_loss: 0.5175
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7882 - loss: 0.5075 - val_accuracy: 0.7662 - val_loss: 0.4819
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7892 - loss: 0.4684 - val_accuracy: 0.7662 - val_loss: 0.4693
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7719 - loss: 0.4722 - val_accuracy: 0.7662 - val_loss: 0.4667
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7777 - loss: 0.4703 - val_accuracy: 0.7662 - val_loss: 0.4712
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7892 - loss: 0.4605 - val_accuracy: 0.7468 - val_loss: 0.4715
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7950 - loss: 0.4444 - val_accuracy: 0.7532 - val_loss: 0.4726
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7892 - loss: 0.4597 - val_accuracy: 0.7597 - val_loss: 0.4718
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8138 - loss: 0.4382 - val_accuracy: 0.7597 - val_loss: 0.4733
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7864 - loss: 0.4384 - val_accuracy: 0.7468 - val_loss: 0.4766
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7895 - loss: 0.4477 - val_accuracy: 0.7468 - val_loss: 0.4762
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7737 - loss: 0.4241 - val_accuracy: 0.7468 - val_loss: 0.4788
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7705 - loss: 0.4617 - val_accuracy: 0.7597 - val_loss: 0.4805
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7928 - loss: 0.4490 - val_accuracy: 0.7662 - val_loss: 0.4762
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7985 - loss: 0.4274 - val_accuracy: 0.7532 - val_loss: 0.4771
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7849 - loss: 0.4561 - val_accuracy: 0.7532 - val_loss: 0.4786
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.4081 - val_accuracy: 0.7468 - val_loss: 0.4756
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8005 - loss: 0.4253 - val_accuracy: 0.7468 - val_loss: 0.4781
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4273 - val_accuracy: 0.7597 - val_loss: 0.4780
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8095 - loss: 0.3970 - val_accuracy: 0.7532 - val_loss: 0.4782
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7854 - loss: 0.4517 - val_accuracy: 0.7597 - val_loss: 0.4787
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7676 - loss: 0.4656 - val_accuracy: 0.7662 - val_loss: 0.4791
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7867 - loss: 0.4543 - val_accuracy: 0.7597 - val_loss: 0.4790
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7716 - loss: 0.4440 - val_accuracy: 0.7792 - val_loss: 0.4777
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7909 - loss: 0.4386 - val_accuracy: 0.7468 - val_loss: 0.4793
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8068 - loss: 0.4201 - val_accuracy: 0.7662 - val_loss: 0.4784
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7918 - loss: 0.4623 - val_accuracy: 0.7662 - val_loss: 0.4846
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7917 - loss: 0.4337 - val_accuracy: 0.7727 - val_loss: 0.4804
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8144 - loss: 0.4183 - val_accuracy: 0.7597 - val_loss: 0.4840
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8057 - loss: 0.4408 - val_accuracy: 0.7727 - val_loss: 0.4835
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8100 - loss: 0.4265 - val_accuracy: 0.7662 - val_loss: 0.4835
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8093 - loss: 0.4278 - val_accuracy: 0.7662 - val_loss: 0.4845
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8019 - loss: 0.4157 - val_accuracy: 0.7597 - val_loss: 0.4799
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8053 - loss: 0.4181 - val_accuracy: 0.7857 - val_loss: 0.4828
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7947 - loss: 0.4257 - val_accuracy: 0.7727 - val_loss: 0.4867
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7862 - loss: 0.4464 - val_accuracy: 0.7727 - val_loss: 0.4875
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7911 - loss: 0.4395 - val_accuracy: 0.7857 - val_loss: 0.4859
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8057 - loss: 0.4331 - val_accuracy: 0.7727 - val_loss: 0.4837
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7923 - loss: 0.4290 - val_accuracy: 0.7727 - val_loss: 0.4803
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8008 - loss: 0.4171 - val_accuracy: 0.7727 - val_loss: 0.4824
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8052 - loss: 0.4220 - val_accuracy: 0.7727 - val_loss: 0.4803
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7951 - loss: 0.4419 - val_accuracy: 0.7727 - val_loss: 0.4824
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8022 - loss: 0.4127 - val_accuracy: 0.7792 - val_loss: 0.4809
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7949 - loss: 0.4285 - val_accuracy: 0.7792 - val_loss: 0.4777
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8090 - loss: 0.4138 - val_accuracy: 0.7727 - val_loss: 0.4826
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8199 - loss: 0.3951 - val_accuracy: 0.7792 - val_loss: 0.4837
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7953 - loss: 0.4410 - val_accuracy: 0.7792 - val_loss: 0.4815
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8053 - loss: 0.4319 - val_accuracy: 0.7792 - val_loss: 0.4802
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8062 - loss: 0.4017 - val_accuracy: 0.7662 - val_loss: 0.4827
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8135 - loss: 0.4029 - val_accuracy: 0.7857 - val_loss: 0.4816
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8162 - loss: 0.4126 - val_accuracy: 0.7727 - val_loss: 0.4815
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8041 - loss: 0.4126 - val_accuracy: 0.7792 - val_loss: 0.4833
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7937 - loss: 0.4299 - val_accuracy: 0.7662 - val_loss: 0.4834
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8128 - loss: 0.3960 - val_accuracy: 0.7792 - val_loss: 0.4829
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8056 - loss: 0.4353 - val_accuracy: 0.7727 - val_loss: 0.4843
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8018 - loss: 0.4178 - val_accuracy: 0.7792 - val_loss: 0.4840
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8215 - loss: 0.3937 - val_accuracy: 0.7987 - val_loss: 0.4857
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8209 - loss: 0.4192 - val_accuracy: 0.7857 - val_loss: 0.4857
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8173 - loss: 0.3935 - val_accuracy: 0.7792 - val_loss: 0.4879
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8258 - loss: 0.3921 - val_accuracy: 0.7922 - val_loss: 0.4837
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8100 - loss: 0.3914 - val_accuracy: 0.7857 - val_loss: 0.4859
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8053 - loss: 0.4302 - val_accuracy: 0.7792 - val_loss: 0.4863
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8240 - loss: 0.3877 - val_accuracy: 0.7922 - val_loss: 0.4849
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7947 - loss: 0.4376 - val_accuracy: 0.7857 - val_loss: 0.4880
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7952 - loss: 0.4177 - val_accuracy: 0.7792 - val_loss: 0.4885
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8264 - loss: 0.3943 - val_accuracy: 0.7922 - val_loss: 0.4907
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8221 - loss: 0.4011 - val_accuracy: 0.7987 - val_loss: 0.4879
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8244 - loss: 0.4029 - val_accuracy: 0.7792 - val_loss: 0.4910
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8195 - loss: 0.3898 - val_accuracy: 0.7922 - val_loss: 0.4935
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7951 - loss: 0.4246 - val_accuracy: 0.7922 - val_loss: 0.4912
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8143 - loss: 0.4117 - val_accuracy: 0.7857 - val_loss: 0.4900
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8050 - loss: 0.4184 - val_accuracy: 0.7792 - val_loss: 0.4895
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8073 - loss: 0.4267 - val_accuracy: 0.7922 - val_loss: 0.4909
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7955 - loss: 0.4215 - val_accuracy: 0.7857 - val_loss: 0.4880
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8259 - loss: 0.4006 - val_accuracy: 0.7857 - val_loss: 0.4890
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8159 - loss: 0.3934 - val_accuracy: 0.7857 - val_loss: 0.4903
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8071 - loss: 0.4294 - val_accuracy: 0.7857 - val_loss: 0.4921
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8266 - loss: 0.3939 - val_accuracy: 0.7857 - val_loss: 0.4929
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8131 - loss: 0.4036 - val_accuracy: 0.8052 - val_loss: 0.4896
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8188 - loss: 0.3858 - val_accuracy: 0.7857 - val_loss: 0.4918
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8034 - loss: 0.4171 - val_accuracy: 0.7597 - val_loss: 0.4986
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8335 - loss: 0.3964 - val_accuracy: 0.7987 - val_loss: 0.4927
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7930 - loss: 0.4413 - val_accuracy: 0.7792 - val_loss: 0.4919
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7992 - loss: 0.4136 - val_accuracy: 0.7857 - val_loss: 0.4940
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8256 - loss: 0.3864 - val_accuracy: 0.7792 - val_loss: 0.4929
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8271 - loss: 0.3720 - val_accuracy: 0.7987 - val_loss: 0.4972
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8121 - loss: 0.4035 - val_accuracy: 0.7987 - val_loss: 0.4924
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8428 - loss: 0.3746 - val_accuracy: 0.7792 - val_loss: 0.4934
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8119 - loss: 0.4022 - val_accuracy: 0.7922 - val_loss: 0.4962
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8222 - loss: 0.3871 - val_accuracy: 0.7857 - val_loss: 0.5003
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8153 - loss: 0.4001 - val_accuracy: 0.7662 - val_loss: 0.4947
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8046 - loss: 0.4121 - val_accuracy: 0.7662 - val_loss: 0.5008
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7986 - loss: 0.4055 - val_accuracy: 0.7727 - val_loss: 0.4984
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8105 - loss: 0.3959 - val_accuracy: 0.7727 - val_loss: 0.5018
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8196 - loss: 0.3803 - val_accuracy: 0.7922 - val_loss: 0.5030
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8140 - loss: 0.3863 - val_accuracy: 0.7792 - val_loss: 0.4998
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8077 - loss: 0.3827 - val_accuracy: 0.7597 - val_loss: 0.4972
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8112 - loss: 0.3951 - val_accuracy: 0.7857 - val_loss: 0.4959
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8422 - loss: 0.3701 - val_accuracy: 0.7662 - val_loss: 0.5006
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8230 - loss: 0.3829 - val_accuracy: 0.7662 - val_loss: 0.5039
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8051 - loss: 0.4074 - val_accuracy: 0.7727 - val_loss: 0.4928
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8258 - loss: 0.3852 - val_accuracy: 0.7597 - val_loss: 0.4991
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8221 - loss: 0.3860 - val_accuracy: 0.7662 - val_loss: 0.5009
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8251 - loss: 0.3925 - val_accuracy: 0.7857 - val_loss: 0.5037
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8199 - loss: 0.4045 - val_accuracy: 0.7727 - val_loss: 0.5027
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8353 - loss: 0.3653 - val_accuracy: 0.7727 - val_loss: 0.5055
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8324 - loss: 0.3692 - val_accuracy: 0.7792 - val_loss: 0.5059
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8413 - loss: 0.3960 - val_accuracy: 0.7597 - val_loss: 0.5050
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8079 - loss: 0.3959 - val_accuracy: 0.7597 - val_loss: 0.5043
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8197 - loss: 0.3753 - val_accuracy: 0.7727 - val_loss: 0.5050
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8580 - loss: 0.3465 - val_accuracy: 0.7857 - val_loss: 0.5099
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8341 - loss: 0.3601 - val_accuracy: 0.7857 - val_loss: 0.5029
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8274 - loss: 0.3856 - val_accuracy: 0.7727 - val_loss: 0.5012
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8284 - loss: 0.3997 - val_accuracy: 0.7792 - val_loss: 0.5100
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8422 - loss: 0.3579 - val_accuracy: 0.7857 - val_loss: 0.5066
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8593 - loss: 0.3524 - val_accuracy: 0.7857 - val_loss: 0.5099
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8538 - loss: 0.3509 - val_accuracy: 0.7857 - val_loss: 0.5143
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8441 - loss: 0.3743 - val_accuracy: 0.7792 - val_loss: 0.5094
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8347 - loss: 0.3790 - val_accuracy: 0.7792 - val_loss: 0.5102
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8424 - loss: 0.3682 - val_accuracy: 0.7792 - val_loss: 0.5131
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8158 - loss: 0.3824 - val_accuracy: 0.7792 - val_loss: 0.5156
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8561 - loss: 0.3599 - val_accuracy: 0.7857 - val_loss: 0.5078
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8304 - loss: 0.3729 - val_accuracy: 0.7597 - val_loss: 0.5121
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8369 - loss: 0.3698 - val_accuracy: 0.7597 - val_loss: 0.5140
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8309 - loss: 0.3643 - val_accuracy: 0.7727 - val_loss: 0.5128
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8726 - loss: 0.3462 - val_accuracy: 0.7597 - val_loss: 0.5100
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8486 - loss: 0.3430 - val_accuracy: 0.7662 - val_loss: 0.5117
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8293 - loss: 0.3872 - val_accuracy: 0.7727 - val_loss: 0.5111
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8565 - loss: 0.3599 - val_accuracy: 0.7597 - val_loss: 0.5152
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8095 - loss: 0.3883 - val_accuracy: 0.7857 - val_loss: 0.5166
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8440 - loss: 0.3674 - val_accuracy: 0.7597 - val_loss: 0.5143
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8520 - loss: 0.3711 - val_accuracy: 0.7662 - val_loss: 0.5170
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8238 - loss: 0.3789 - val_accuracy: 0.7727 - val_loss: 0.5177
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8500 - loss: 0.3642 - val_accuracy: 0.7792 - val_loss: 0.5176
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8597 - loss: 0.3477 - val_accuracy: 0.7662 - val_loss: 0.5219
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8357 - loss: 0.3695 - val_accuracy: 0.7662 - val_loss: 0.5176
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8644 - loss: 0.3525 - val_accuracy: 0.7597 - val_loss: 0.5275
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8565 - loss: 0.3399 - val_accuracy: 0.7662 - val_loss: 0.5310
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8616 - loss: 0.3570 - val_accuracy: 0.7662 - val_loss: 0.5245
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8676 - loss: 0.3451 - val_accuracy: 0.7792 - val_loss: 0.5258
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8335 - loss: 0.3926 - val_accuracy: 0.7727 - val_loss: 0.5240
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8390 - loss: 0.3667 - val_accuracy: 0.7662 - val_loss: 0.5363
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8616 - loss: 0.3349 - val_accuracy: 0.7532 - val_loss: 0.5367
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8664 - loss: 0.3327 - val_accuracy: 0.7727 - val_loss: 0.5327
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8563 - loss: 0.3422 - val_accuracy: 0.7597 - val_loss: 0.5347
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8658 - loss: 0.3363 - val_accuracy: 0.7532 - val_loss: 0.5331
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8615 - loss: 0.3299 - val_accuracy: 0.7662 - val_loss: 0.5441
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8644 - loss: 0.3459 - val_accuracy: 0.7532 - val_loss: 0.5347
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8776 - loss: 0.3244 - val_accuracy: 0.7597 - val_loss: 0.5411
Epoch 162/200